IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_HEIGHT: 30 # 최대 380까지
  ROI_Y_POS: 350 # 300

LANE:
  LANE_WIDTH: 490
  OFFSET: 365

HOUGH:
  THRESHOLD: 20
  MIN_LINE_LENGTH: 15

XYCAR:
  START_SPEED: 15.0 # 15.0
  MAX_SPEED: 15 # 15.0
  MIN_SPEED: 7.0 # 7.0
  UP_STEP_SPEED: 0.15
  DOWN_STEP_SPEED: 0.4 #0.4

PID:
  P_GAIN: 0.35 #0.35 
  I_GAIN: 0.0007 #0.0007 
  D_GAIN: 0.08 #0.08 

KALMAN:
  SLOPE_DER: -0.015 # -0.02
  INTERCEPT_DER: -25.0 # -3.0

VIDEO:
  VIDEO_NAME: test51.avi

# MOVING_AVERAGE_FILTER:
#   SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
