IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_HEIGHT: 30 # 최대 380까지
  ROI_Y_POS: 350 # 300

LANE:
  LANE_WIDTH: 490
  OFFSET: 365

XYCAR:
  START_SPEED: 12.0
  MAX_SPEED: 20.0
  MIN_SPEED: 5.0
  UP_STEP_SPEED: 0.1
  DOWN_STEP_SPEED: 0.2

PID:
  P_GAIN: 0.6 # 0.6
  I_GAIN: 0.0002 # 0.0004 # 0.0006
  D_GAIN: 0.05 # 0.05 # 0.025

KALMAN:
  SLOPE_DER: -0.015 # -0.02
  INTERCEPT_DER: -25.0 # -3.0

VIDEO:
  VIDEO_NAME: test43.avi

# MOVING_AVERAGE_FILTER:
#   SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
